# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiDissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('publication', models.CharField(max_length=255)),
            ],
        ),
    ]
