# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0002_esidissertation'),
    ]

    operations = [
        migrations.AddField(
            model_name='esidissertation',
            name='add2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='esidissertation',
            name='add3',
            field=models.CharField(default=b'1', max_length=10),
        ),
        migrations.AddField(
            model_name='esidissertation',
            name='add4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='esidissertation',
            name='add5',
            field=models.CharField(default=b'1', max_length=10),
        ),
        migrations.AddField(
            model_name='esidissertation',
            name='context',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='esidissertation',
            name='index',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='esidissertation',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='esidissertation',
            name='publication',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esidissertation',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
