# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0003_auto_20170508_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esidissertation',
            name='add2',
        ),
        migrations.RemoveField(
            model_name='esidissertation',
            name='add3',
        ),
        migrations.RemoveField(
            model_name='esidissertation',
            name='add4',
        ),
        migrations.RemoveField(
            model_name='esidissertation',
            name='add5',
        ),
    ]
