# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0005_locationconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=500, null=True)),
                ('DATE', models.CharField(max_length=100, null=True)),
                ('AULIST', models.CharField(max_length=500, null=True)),
                ('AUWUST', models.CharField(max_length=100, null=True)),
                ('PUBLICATION', models.CharField(max_length=100, null=True)),
                ('CATECORY', models.CharField(max_length=100, null=True)),
                ('WOSID', models.CharField(max_length=100, null=True)),
                ('WOSCATE', models.CharField(max_length=500, null=True)),
                ('RESEARCHDIR', models.CharField(max_length=500, null=True)),
                ('REFERCOUNT', models.IntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='refer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=500, null=True)),
                ('REFERENCE_TITLE', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
