# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0006_dissertation_refer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='AULIST',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='TITLE',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
