# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connor', '0007_auto_20170613_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='MECHANISM',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='REFERCOUNT',
            field=models.IntegerField(null=True),
        ),
    ]
